build:
  stage: build
  before_script:
    - chmod +x ./mvnw
  script:
    - ./mvnw clean package
  only:
    - tags
  artifacts:
    paths:
    - target/*.jar
  cache:
    key: "$CI_BUILD_NAME"
    untracked: true
    paths:
    - target/
  tags:
    - java8
