# Pull base image
FROM resin/rpi-raspbian:latest

LABEL maintainer="Tobias Hargesheimer <docker@ison.ws>"
LABEL description="TelefonWahnsinn (PhoneMadness): \
A Application written in JAVA monitors various sensors (Telephone -Innovaphone-, Fritz!Box, doorsensor) and \
switched accordingly the music (player: MPD, XBMC or VLC) to stop/pause or play."

ENV LANG C.UTF-8

RUN [ "cross-build-start" ]

# Install dependencies
RUN apt-get update && apt-get install -y \
    openjdk-8-jre \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-armhf

ADD target/TelefonWahnsinn-jar-with-dependencies.jar /TelefonWahnsinn.jar
COPY config /config

RUN [ "cross-build-end" ]

VOLUME ["/config","/sys/class/gpio"]

# Define default command
CMD ["java","-jar","/TelefonWahnsinn.jar"]
