# Pull base image
FROM resin/rpi-raspbian:latest

LABEL maintainer="Tobias Hargesheimer <docker@ison.ws>"
LABEL description="TelefonWahnsinn (PhoneMadness): \
A Application written in JAVA monitors various sensors (Telephone -Innovaphone-, Fritz!Box, doorsensor) and \
switched accordingly the music (player: MPD, XBMC or VLC) to stop/pause or play."

ENV LANG C.UTF-8

#RUN [ "cross-build-start" ]

# Install dependencies
RUN apt-get update && apt-get install -y \
	git \
	wget \
	openjdk-8-jre \
	openjdk-8-jdk \
	ca-certificates-java \
	--no-install-recommends && \
	rm -rf /var/lib/apt/lists/* && \
	/var/lib/dpkg/info/ca-certificates-java.postinst configure

# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-armhf
# Repository 
ENV REPOSITORY https://github.com/TobiasH87/de.hs-mainz.telefonwahnsinn.git

# Build Java Application 
RUN git clone ${REPOSITORY} PhoneMadness/ \
	&& cd PhoneMadness/ \
	&& chmod +x mvnw \
	&& ./mvnw clean package \
	&& cp target/TelefonWahnsinn-jar-with-dependencies.jar /TelefonWahnsinn.jar \
	&& mkdir /config && cp config/config.xml.example /config/config.xml \
	&& cd .. && rm -r PhoneMadness/ 

#RUN [ "cross-build-end" ]

# Define Volumes
VOLUME ["/config","/sys/class/gpio"]

# Define default command
CMD ["java","-jar","/TelefonWahnsinn.jar"]
