FROM resin/raspberry-pi-alpine:3.6

LABEL maintainer="Tobias Hargesheimer <docker@ison.ws>"
LABEL description="TelefonWahnsinn (PhoneMadness): \
A Application written in JAVA monitors various sensors (Telephone -Innovaphone-, Fritz!Box, doorsensor) and \
switched accordingly the music (player: MPD, XBMC or VLC) to stop/pause or play."

ENV LANG C.UTF-8

RUN [ "cross-build-start" ]

RUN set -x && \
	apk --no-cache add \
	openjdk8-jre

ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk/jre
ENV PATH $PATH:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin

ADD target/TelefonWahnsinn-jar-with-dependencies.jar /TelefonWahnsinn.jar
COPY config /config

RUN [ "cross-build-end" ]

VOLUME ["/config","/sys/class/gpio"]

CMD ["java","-jar","/TelefonWahnsinn.jar"]
